# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comset.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_comsetform(object):
    def setupUi(self, comsetform):
        comsetform.setObjectName("comsetform")
        comsetform.resize(213, 193)
        self.label = QtWidgets.QLabel(comsetform)
        self.label.setGeometry(QtCore.QRect(24, 26, 54, 16))
        self.label.setObjectName("label")
        self.cb_com = QtWidgets.QComboBox(comsetform)
        self.cb_com.setGeometry(QtCore.QRect(90, 26, 101, 20))
        self.cb_com.setObjectName("cb_com")
        self.cb_bsp = QtWidgets.QComboBox(comsetform)
        self.cb_bsp.setGeometry(QtCore.QRect(90, 52, 101, 20))
        self.cb_bsp.setFrame(True)
        self.cb_bsp.setObjectName("cb_bsp")
        self.cb_bsp.addItem("")
        self.cb_bsp.addItem("")
        self.cb_bsp.addItem("")
        self.cb_bsp.addItem("")
        self.cb_bsp.addItem("")
        self.cb_bsp.addItem("")
        self.label_2 = QtWidgets.QLabel(comsetform)
        self.label_2.setGeometry(QtCore.QRect(24, 52, 54, 16))
        self.label_2.setObjectName("label_2")
        self.cb_data = QtWidgets.QComboBox(comsetform)
        self.cb_data.setGeometry(QtCore.QRect(90, 78, 101, 20))
        self.cb_data.setObjectName("cb_data")
        self.cb_data.addItem("")
        self.cb_data.addItem("")
        self.label_3 = QtWidgets.QLabel(comsetform)
        self.label_3.setGeometry(QtCore.QRect(24, 78, 54, 16))
        self.label_3.setObjectName("label_3")
        self.cb_stop = QtWidgets.QComboBox(comsetform)
        self.cb_stop.setGeometry(QtCore.QRect(90, 130, 101, 20))
        self.cb_stop.setObjectName("cb_stop")
        self.cb_stop.addItem("")
        self.cb_stop.addItem("")
        self.cb_stop.addItem("")
        self.label_4 = QtWidgets.QLabel(comsetform)
        self.label_4.setGeometry(QtCore.QRect(24, 130, 54, 16))
        self.label_4.setObjectName("label_4")
        self.cb_p = QtWidgets.QComboBox(comsetform)
        self.cb_p.setGeometry(QtCore.QRect(90, 104, 101, 20))
        self.cb_p.setObjectName("cb_p")
        self.cb_p.addItem("")
        self.cb_p.addItem("")
        self.cb_p.addItem("")
        self.label_5 = QtWidgets.QLabel(comsetform)
        self.label_5.setGeometry(QtCore.QRect(24, 104, 54, 16))
        self.label_5.setObjectName("label_5")
        self.btn_default = QtWidgets.QPushButton(comsetform)
        self.btn_default.setGeometry(QtCore.QRect(84, 160, 50, 23))
        self.btn_default.setObjectName("btn_default")
        self.btn_save = QtWidgets.QPushButton(comsetform)
        self.btn_save.setGeometry(QtCore.QRect(24, 160, 50, 23))
        self.btn_save.setObjectName("btn_save")
        self.btn_esc = QtWidgets.QPushButton(comsetform)
        self.btn_esc.setGeometry(QtCore.QRect(144, 160, 50, 23))
        self.btn_esc.setObjectName("btn_esc")

        self.retranslateUi(comsetform)
        self.cb_bsp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(comsetform)

    def retranslateUi(self, comsetform):
        _translate = QtCore.QCoreApplication.translate
        comsetform.setWindowTitle(_translate("comsetform", "串口设置"))
        self.label.setText(_translate("comsetform", "串口"))
        self.cb_bsp.setCurrentText(_translate("comsetform", "115200"))
        self.cb_bsp.setItemText(0, _translate("comsetform", "115200"))
        self.cb_bsp.setItemText(1, _translate("comsetform", "4800"))
        self.cb_bsp.setItemText(2, _translate("comsetform", "9600"))
        self.cb_bsp.setItemText(3, _translate("comsetform", "19200"))
        self.cb_bsp.setItemText(4, _translate("comsetform", "38400"))
        self.cb_bsp.setItemText(5, _translate("comsetform", "57600"))
        self.label_2.setText(_translate("comsetform", "波特率"))
        self.cb_data.setCurrentText(_translate("comsetform", "8"))
        self.cb_data.setItemText(0, _translate("comsetform", "8"))
        self.cb_data.setItemText(1, _translate("comsetform", "7"))
        self.label_3.setText(_translate("comsetform", "数据位"))
        self.cb_stop.setItemText(0, _translate("comsetform", "1"))
        self.cb_stop.setItemText(1, _translate("comsetform", "1.5"))
        self.cb_stop.setItemText(2, _translate("comsetform", "2"))
        self.label_4.setText(_translate("comsetform", "停止位"))
        self.cb_p.setItemText(0, _translate("comsetform", "NONE"))
        self.cb_p.setItemText(1, _translate("comsetform", "ODD"))
        self.cb_p.setItemText(2, _translate("comsetform", "EVEN"))
        self.label_5.setText(_translate("comsetform", "校验位"))
        self.btn_default.setText(_translate("comsetform", "默认"))
        self.btn_save.setText(_translate("comsetform", "确定"))
        self.btn_esc.setText(_translate("comsetform", "取消"))

